name: .NET Build and Test

on:
  push:
    branches:
      - main
      - test-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24
        options: --privileged
        ports:
          - 5432:5432
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.402'

      - name: Check Docker status
        run: docker info

      - name: Check .NET SDK version
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore --verbosity normal

      - name: Build solution
        run: dotnet build --no-restore --verbosity normal --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Debug after failure
        if: failure()
        run: |
          echo "Listing current directory contents:"
          ls -la
          echo "Environment variables:"
          env