name: .NET Build and Test

on:
  push:
    branches:
      - main
      - test-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.402'

      - name: Restore dependencies
        run: dotnet restore

        # Build the project (Debug Configuration for Testing)
      - name: Build for Testing
        run: dotnet build --no-restore --configuration Debug --verbosity normal

        # Run tests (Debug Configuration)
      - name: Run Tests with Debug Configuration
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

        # Build the project (Release Configuration for Production Validation)
      - name: Build for Release
        run: dotnet build --no-restore --configuration Release --verbosity normal